### ISSUE TITLE
Possibly error in Bison Source file.

### ISSUE THREAD

**Issue by LeonardKoenig** [Croteam-official/Serious-Engine#17] opened 2016-03-13 00:43 UTC
At least I get:

```
Serious-Engine/Sources/Ecc/Parser.y:1076:96: error: expected ‘;’ before ‘}’ token
```

snippet (3rd line here is 1076 line in source):

```Yacc
statement
  : expression ';' {$$=$1+$2;}
  | k_switch '(' expression ')' '{' statements '}' {$$=$1+$2+$3+$4+$5+$6+$7}
  | k_case case_constant_expression ':' {$$=$1+" "+$2+$3+" ";}
  | '{' statements '}' {$$=$1+$2+$3;}
  | expression '{' statements '}' {$$=$1+$2+$3+$4;}
```

This seems correct as it's the only one where there's no ';' before the closing brace. I fixed this locally and on my devel branch and it builds correctly with this fix -- but I'm no expert in Bison so you might want to look into this yourself.

**Comment by SLAwww** [comment] 2016-03-13 00:50
Unfortunately I cannot reproduce that, ECC builds fine for me. Are you using a version of Bison supplied with the engine? Does anyone else encounter this?

**Comment by LeonardKoenig** [comment] 2016-03-13 00:54
Well, I think it works because it's not regenerated as you already supply a version. Possibly deleting the Parser.h/Parser.cpp file would do the trick of reproducing.

I'm actually building on Linux (Bison 3.0.4) but this does seem to be an issue anyway and nothing that *should* relate to the version (except that maybe your build tolerated the issue and just moved on or something).

**Comment by SLAwww** [comment] 2016-03-13 01:01
I deleted all generated files before building, including Parser.h/Parser.cpp. I'm not an expert in Bison unfortunately, so I should see if your proposed change makes any difference in files generated by ECC.

**Comment by LeonardKoenig** [comment] 2016-03-13 01:06
Okay, I try to reproduce on Windows as soon as I get on my Windows machine again, too ;-)

**Comment by yamgent** [comment] 2016-03-13 12:04
The .y file compiles fine on the older version of Bison because the older version automatically inserts a semi-colon to the end of every statement, thus there were no such issues (in fact statements with semi-colon ended up with 2 semicolons on the generated parser source).

However, the newer version of Bison does not do that (which makes more sense tbh). Can confirm the same error as @LeonardKoenig, on cygwin32's Bison (3.0.4).

Since the older version of the bison executable is in the repo, @SLAwww your call on whether this should be fixed. I think no harm is done to fix this minor error though.

**Comment by LeonardKoenig** [comment] 2016-03-13 14:01
@yamgent Thanks for the explanation! Yes, it really generates an additional ';' which is a NOP for the C/C++ code.
And since all the other statements put a ';' at the end and it's more compatible it wouldn't do any harm there either.

**Comment by SLAwww** [comment] 2016-03-13 16:57
Okay, I agree with @yamgent on this one, commit https://github.com/Croteam-official/Serious-Engine/commit/6e9fbef44a33c8df63ee2aa203c0a00ac6d4ad9f should contain the fix.

**Closed by SLAwww** 2016-03-13 16:57 UTC
